# Generated by Django 5.2.7 on 2025-10-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='user',
            new_name='usuario',
        ),
    ]
